[[snippets]]
  description = "Remove docker images"
  command = "docker images | grep none | awk \"{ print $3; }\" | xargs docker rmi -f"
  output = ""

[[snippets]]
  description = "Remove docker containers"
  command = "docker container rm $(docker container ls -aq)"
  output = ""

[[snippets]]
  description = "Interactive shell in a docker container with current directory mounted"
  command = "docker run --rm -it -v $PWD:/work -w /work <docker-image-name>"
  output = ""

[[snippets]]
  description = "Remove all exif metadata from a file"
  command = "exiftool -All= <file>"
  output = ""

[[snippets]]
  description = "start virtualbox vm machine in headless mode"
  command = "VBoxManage startvm <machine=\"ROS-Ubuntu\"> --type headless"
  output = ""

[[snippets]]
  description = "power off virtualbox vm machine"
  command = "VBoxManage controlvm <machine=\"ROS-Ubuntu\"> <method=poweroff>"
  output = ""

[[snippets]]
  description = "Count the number of non-empty lines across all python files"
  command = "fd -t f -g \"*.py\" -E \"__init__.py\" . -X cat -b | tail -n 1 | awk '{print $1}' | tr -d '[:space:]'"
  output = ""

[[snippets]]
  description = "convert audio to mp3"
  command = "ffmpeg -i <input_file> -vn -ar <sample_rate=44100> -ac <channels=2> -b:a <bitrate=192K> <output_file?"
  output = ""

[[snippets]]
  description = "download youtube audio with ytfzf"
  command = "ytfzf --download --audio-only -t <query>"
