[theme]
name = "slick"

[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G}/{mem_total;G}({mem_used_percents}%)"
format_swap = "{swap_used;G}/{swap_total;G}({swap_used_percents}%)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "backlight"

[[block]]
block = "sound"
step_width = 10
max_vol = 100
show_volume_when_muted = true

[[block]]
block = "networkmanager"
on_click = "terminator -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "proton\\d+"]
interface_name_include = []
ap_format = "{ssid}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
good = 75
info = 30
warning = 15
critical = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
