[[snippets]]
  description = "Remove docker images"
  command = "docker images | grep none | awk \"{ print $3; }\" | xargs docker rmi -f"
  output = ""

[[snippets]]
  description = "Remove docker containers"
  command = "docker container rm $(docker container ls -aq)"
  output = ""

[[snippets]]
  description = "gcloud sdk shell"
  command = "docker run --rm -it gcr.io/google.com/cloudsdktool/cloud-sdk"
  output = ""

[[snippets]]
  description = "Interactive shell in a docker container with current directory mounted"
  command = "docker run --rm -it -v $PWD:/work -w /work <docker-image-name>"
  output = ""

[[snippets]]
  description = "Remove all exif metadata from a file"
  command = "exiftool -All= <file>"
  output = ""

[[snippets]]
  description = "Create a docker buildx builder with insecure entitlements"
  command = "docker buildx create --name <builderName=mybuilder> --buildkitd-flags \"--allow-insecure-entitlement network.host\" --config <config=config.toml> --driver-opt network=host --use"
  output = ""

[[snippets]]
  description = "Build multi-arch docker container with buildx and push to registry on local network"
  command = "docker buildx build --allow=network.host --tag cluster:30500/<containerName> --add-host=cluster:<WorkerIp=192.168.0.70> --platform linux/amd64,linux/arm64 --push ."
  output = ""

[[snippets]]
  description = "start virtualbox vm machine in headless mode"
  command = "VBoxManage startvm <machine=\"Ubuntu Server LFS201\"> --type headless"
  output = ""

[[snippets]]
  description = "power off virtualbox vm machine"
  command = "VBoxManage controlvm <machine=\"Ubuntu Server LFS201\"> <method=poweroff>"
  output = ""
