[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome5"

#[[block]]
#block = "pacman"
#interval = 600
#format = "{pacman} + {aur} = {both} updates"
#format_singular = "{both} updates available"
#format_up_to_date = "system up to date"
#critical_updates_regex = "(linux|linux-lts|linux-zen)"
## aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
#aur_command = "yay -Qua"
#hide_when_uptodate = true

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 3

[[block]]
block = "backlight"

[[block]]
block = "sound"
step_width = 10
max_vol = 100
show_volume_when_muted = true

[[block]]
block = "net"
format = " $icon {$ssid|} $device "

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d-%m %R') "
short = " $icon $timestamp.datetime(f:%R) "
